<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Home

wp_enqueue_style( 'grabjet-home', get_template_directory_uri() . '/home.css' );

// Reposition the primary navigation menu
remove_action( 'genesis_after_header', 'genesis_do_nav' );
add_action( 'genesis_header', 'genesis_do_nav', 12 );

// Remove .wrap from menu-primary or other element by omitting them from the array below
add_theme_support( 'genesis-structural-wraps', array('header', 'footer') );

// Remove Genesis sidebars
remove_action( 'genesis_sidebar', 'genesis_do_sidebar' );
remove_action( 'genesis_sidebar_alt', 'genesis_do_sidebar_alt' );

// Remove Footer and Display Second Nav Menu
 
remove_action( 'genesis_after_header', 'genesis_do_subnav' );
add_action( 'genesis_footer', 'genesis_do_subnav' );

//Changing the Credits
function grabjet_footer_copyright () {
	echo '<p class="grabjet-copy">Copyright ';
	echo '<a href="https://grab.com">Grab.com</a> '. date('Y') .'. All Rights Reserved.</p>';
}
add_filter( 'genesis_footer_creds_text', 'grabjet_footer_copyright' );

// Add .container-fluid to header and footer
add_filter( 'genesis_attr_site-header', 'grabjet_header_container_fluid' );
function grabjet_header_container_fluid( $attributes ) {
 
 // add original plus extra CSS classes
 $attributes['class'] .= ' container-fluid';
 
 // return the attributes
 return $attributes;
}

add_filter( 'genesis_attr_site-footer', 'grabjet_footer_container_fluid' );
function grabjet_footer_container_fluid( $attributes ) {
 
 // add original plus extra CSS classes
 $attributes['class'] .= ' container-fluid';
 
 // return the attributes
 return $attributes;
}

// Reponsive Menu

// Add skip link needs to secondary nav
add_filter( 'genesis_attr_nav-secondary', 'leaven_add_nav_secondary_id' );
function leaven_add_nav_secondary_id( $attributes ) {
	$attributes['id'] = 'genesis-nav-secondary';
	return $attributes;
}
add_filter( 'genesis_skip_links_output', 'leaven_add_nav_secondary_skip_link' );
function leaven_add_nav_secondary_skip_link( $links ) {
	$new_links = $links;
	array_splice( $new_links, 1 );
	if ( has_nav_menu( 'secondary' ) ) {
		$new_links['genesis-nav-secondary'] = __( 'Skip to secondary navigation', 'leaven' );
	}
	return array_merge( $new_links, $links );
}

// Required Scripts and Styles
add_action( 'wp_enqueue_scripts', 'leaven_load_scripts', 15 );
function leaven_load_scripts() {
	// Responsive Navigation
	wp_enqueue_style( 'fontawesome', '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', array(), '4.3.0' );
	wp_enqueue_script( 'leaven-responsive-menu', get_stylesheet_directory_uri() . '/responsive-menu.js', array( 'jquery' ), '1.0.0', true );
	$output = array(
		'mainMenu' => __( '', 'leaven' ),
		'subMenu'  => __( '', 'leaven' ),
	);
	wp_localize_script( 'leaven-responsive-menu', 'LeavenL10n', $output );
}


genesis();
